[Header]Comecando o header para tablet mobile e desk
juliaAparecida/hipstersjobs pull request #1
Opened 2020-04-07 17:03 UTC by juliaAparecida

2020-04-07 22:33 UTC, anderson-figueiredo requested changes
Foi um bom começo, gostei de já ter criado um padrão de classes pro css. Fica mais fácil de escalar.

2020-04-07 22:33 UTC, anderson-figueiredo commented on cabecalho.html
> +        <img class="cabecalho__logo" src="../hipstersjobs/img/hipsters-jobs-logo.png" at="logo do hipsters-jobs">
Bom ter se atentado em colocar o texto alternativo, só precisa corrigir o atributo `alt`

2020-04-07 22:33 UTC, anderson-figueiredo commented on css/cabecalho.css
> +    margin: 2.4rem 1rem 1rem 1rem;
Não está errado, mas não precisaria do terceiro `1rem`

2020-04-07 22:33 UTC, anderson-figueiredo commented on css/cabecalho.css
> +        margin: 2.2rem 1rem 1rem;
Aqui poderia ser só o `margin-top` dado que os outros valores continuam os mesmos

2020-04-08 18:47 UTC, juliaAparecida commented on css/cabecalho.css
> +    margin: 2.4rem 1rem 1rem 1rem;
isso mesmo, não faz diferença ter ou não, o resultado ficaria  da mesma forma

2020-04-08 18:47 UTC, juliaAparecida commented on css/cabecalho.css
> +        margin: 2.2rem 1rem 1rem;
Verdade!!!!

2020-04-08 18:48 UTC, juliaAparecida commented on cabecalho.html
> +        <img class="cabecalho__logo" src="../hipstersjobs/img/hipsters-jobs-logo.png" at="logo do hipsters-jobs">
eu não entendi, o que tem de errado no alt?

2020-04-09 12:37 UTC, anderson-figueiredo commented on cabecalho.html
> +        <img class="cabecalho__logo" src="../hipstersjobs/img/hipsters-jobs-logo.png" at="logo do hipsters-jobs">
`at="logo` deveria ser `alt=logo`

2020-04-09 19:13 UTC, juliaAparecida commented on cabecalho.html
> +        <img class="cabecalho__logo" src="../hipstersjobs/img/hipsters-jobs-logo.png" at="logo do hipsters-jobs">
Na verdade o alt tem "" sim

2020-04-09 20:17 UTC, anderson-figueiredo commented on cabecalho.html
> +        <img class="cabecalho__logo" src="../hipstersjobs/img/hipsters-jobs-logo.png" at="logo do hipsters-jobs">
pera... que meu comentario foi errado.
`at="logo"` deveria ser `alt="logo"`

2020-04-13 22:02 UTC, anderson-figueiredo approved these changes

2020-04-14 17:13 UTC, merged