[Footer]Finalizando o footer nas tres versoes
juliaAparecida/hipstersjobs pull request #2
Opened 2020-04-14 19:27 UTC by juliaAparecida

2020-04-15 12:44 UTC, anderson-figueiredo requested changes
Agora que tem os elementos fixos, acho que já pode definir o espaçamento do container pra se guiar.

2020-04-15 12:44 UTC, anderson-figueiredo commented on css/footer.css
> +	span {
Cuidado ao utilizar as tags na estilização, pode alterar elementos que não deveria

2020-04-15 12:44 UTC, anderson-figueiredo commented on css/footer.css
> +	text-align: center;
Os títulos só são centralizados no mobile. No tablet, desktop seguem o posicionamento padrão.

2020-04-16 15:15 UTC, juliaAparecida commented on css/footer.css
> +	span {
Esqueci desse carinha ai, já vou dá um nome de classe pra ele

2020-04-16 16:16 UTC, anderson-figueiredo approved these changes

2020-04-16 16:22 UTC, merged